### PR TITLE
Adding sample data

### PR DESCRIPTION
**Pull request by mervinpan**
@dkancalade @GalaDev @imartinez8 

I'm adding this updated JSON sample data sheet into my repo in case anyone needs it. This is how I intend to populate the product services. 

- To add clarification, the first product on the list is our product from https://www.etsy.com/listing/549504785/pokenatomy-the-science-of-pokemon-an?show_sold_out_detail=1&ref=anchored_listing&frs=1.

- productDescription seems to be product # specific and doesn't change with styling. 

- versions is the selector portion. These can be changed upon product input based on how the seller inputs their product. For example, our product has a selector 'style'; however, others may have 'color' or 'material'.

Please let me know if you have any questions or suggestions. Thanks.

### CODE REVIEW

**Comment by GalaDev** [comment]
Hey @mervinpan, just realized there is no "price" on products. Do you want to include a "normal price" and "sale/current price" property?

**Comment by GalaDev** [comment]
Also, need a "seller name" and "free shipping = true/false" on each product. Thanks, Mervin!

**Comment by imartinez8** [comment]
Yeah, what @GalaDev mentioned, we should need a price and sale price in case it is on sale, seller name (or would we want to make a table for seller name? Probably not necessary for MVP) we should think about what other product attributes we want to include in todays class depending on what each service needs.

**Comment by mervinpan** [comment]
@GalaDev I was thinking that. But that would be in the distribution, inventory, or user service. Magee said quantity, for example, isn't a part of the product service. So I only kept product details. What are your thoughts?

**Comment by GalaDev** [comment]
@mervinpan  For sure. It's a tough call on how much complexity we want to add. I always vote to keep things as simple as possible haha. Let's all brainstorm during class.

**Pull request merged**
